name: unit test
run-name: ${{ github.actor }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - name: Fetch required Go modules
        run: |
              cd backend
              go mod download
      - name: Build & Test
        run: |
              cd backend
              go get go.mod
              go build -v backend/...
              go test -v backend/...